"""
movies_data.py
──────────────
Curated dataset of 50 popular movies.
Each movie contains the same fields that TMDB metadata CSVs provide:
  id, title, genres, cast, director, keywords, overview, vote_average, release_year
This file acts as the local knowledge-base for the ML engine.
"""

MOVIES = [
    {"id": 27205,  "title": "Inception",            "genres": "action thriller science fiction adventure",
     "cast": "leonardo dicaprio joseph gordon levitt elliot page tom hardy",
     "director": "christopher nolan",
     "keywords": "dream heist mind subconscious layers reality",
     "overview": "A thief who steals corporate secrets through the use of dream-sharing technology.",
     "vote_average": 8.8, "release_year": 2010},

    {"id": 157336, "title": "Interstellar",         "genres": "adventure drama science fiction",
     "cast": "matthew mcconaughey anne hathaway jessica chastain matt damon",
     "director": "christopher nolan",
     "keywords": "space wormhole black hole time dilation nasa survival",
     "overview": "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
     "vote_average": 8.6, "release_year": 2014},

    {"id": 155,    "title": "The Dark Knight",      "genres": "action crime drama thriller",
     "cast": "christian bale heath ledger gary oldman aaron eckhart",
     "director": "christopher nolan",
     "keywords": "batman joker gotham chaos vigilante superhero",
     "overview": "Batman raises the stakes in his war on crime with the help of Lt. Jim Gordon and DA Harvey Dent.",
     "vote_average": 9.0, "release_year": 2008},

    {"id": 19995,  "title": "Avatar",               "genres": "action adventure fantasy science fiction",
     "cast": "sam worthington zoe saldana sigourney weaver stephen lang",
     "director": "james cameron",
     "keywords": "alien planet pandora na vi military nature environment",
     "overview": "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following orders.",
     "vote_average": 7.8, "release_year": 2009},

    {"id": 24428,  "title": "The Avengers",         "genres": "action adventure science fiction",
     "cast": "robert downey jr chris evans scarlett johansson chris hemsworth",
     "director": "joss whedon",
     "keywords": "superhero marvel team iron man thor hulk teamwork",
     "overview": "Earth's mightiest heroes must come together to stop Loki and his alien army.",
     "vote_average": 8.0, "release_year": 2012},

    {"id": 299536, "title": "Avengers Infinity War", "genres": "action adventure science fiction",
     "cast": "robert downey jr chris hemsworth mark ruffalo chris evans josh brolin",
     "director": "anthony russo joe russo",
     "keywords": "thanos infinity stones marvel superhero sacrifice snap",
     "overview": "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat Thanos.",
     "vote_average": 8.5, "release_year": 2018},

    {"id": 603,    "title": "The Matrix",            "genres": "action science fiction",
     "cast": "keanu reeves laurence fishburne carrie anne moss hugo weaving",
     "director": "lana wachowski lilly wachowski",
     "keywords": "simulation virtual reality hacker chosen one red pill blue pill",
     "overview": "A computer hacker learns that reality is a simulation run by machines.",
     "vote_average": 8.7, "release_year": 1999},

    {"id": 680,    "title": "Pulp Fiction",          "genres": "thriller crime drama",
     "cast": "john travolta samuel l jackson uma thurman bruce willis",
     "director": "quentin tarantino",
     "keywords": "crime nonlinear narrative hitman redemption drugs",
     "overview": "The lives of two mob hitmen, a boxer, and a pair of diner bandits intertwine.",
     "vote_average": 8.9, "release_year": 1994},

    {"id": 238,    "title": "The Godfather",         "genres": "crime drama",
     "cast": "marlon brando al pacino james caan diane keaton",
     "director": "francis ford coppola",
     "keywords": "mafia family power crime loyalty corruption",
     "overview": "The aging patriarch of an organized crime dynasty transfers control to his reluctant son.",
     "vote_average": 9.2, "release_year": 1972},

    {"id": 424,    "title": "Schindler's List",      "genres": "drama history war",
     "cast": "liam neeson ben kingsley ralph fiennes",
     "director": "steven spielberg",
     "keywords": "holocaust world war ii nazi jewish rescue humanity",
     "overview": "In German-occupied Poland, Oskar Schindler saves the lives of over a thousand mostly Polish-Jewish refugees.",
     "vote_average": 8.9, "release_year": 1993},

    {"id": 278,    "title": "The Shawshank Redemption", "genres": "drama crime",
     "cast": "tim robbins morgan freeman bob gunton william sadler",
     "director": "frank darabont",
     "keywords": "prison friendship hope redemption escape justice",
     "overview": "Two imprisoned men bond over years, finding solace and redemption through acts of decency.",
     "vote_average": 9.3, "release_year": 1994},

    {"id": 13,     "title": "Forrest Gump",          "genres": "comedy drama romance",
     "cast": "tom hanks robin wright gary sinise sally field",
     "director": "robert zemeckis",
     "keywords": "life journey kindness history vietnam love running",
     "overview": "The history of the United States from the 1950s to the 1970s unfolds from the perspective of Forrest Gump.",
     "vote_average": 8.8, "release_year": 1994},

    {"id": 11,     "title": "Star Wars",             "genres": "action adventure fantasy science fiction",
     "cast": "mark hamill harrison ford carrie fisher alec guinness",
     "director": "george lucas",
     "keywords": "jedi force galaxy rebellion empire lightsaber space opera",
     "overview": "Luke Skywalker joins forces with a Jedi Knight to rescue a princess and save the galaxy.",
     "vote_average": 8.6, "release_year": 1977},

    {"id": 1891,   "title": "The Empire Strikes Back", "genres": "action adventure fantasy science fiction",
     "cast": "mark hamill harrison ford carrie fisher billy dee williams",
     "director": "irvin kershner",
     "keywords": "jedi force yoda darth vader lightsaber rebellion training",
     "overview": "After the Rebels are brutally overpowered by the Empire, Luke begins Jedi training with Yoda.",
     "vote_average": 8.7, "release_year": 1980},

    {"id": 120,    "title": "The Lord of the Rings The Fellowship of the Ring",
     "genres": "adventure fantasy action",
     "cast": "elijah wood ian mckellen viggo mortensen orlando bloom cate blanchett",
     "director": "peter jackson",
     "keywords": "ring quest fellowship middle earth hobbit wizard elf dwarf",
     "overview": "A meek Hobbit and his companions begin a journey to destroy the One Ring.",
     "vote_average": 8.8, "release_year": 2001},

    {"id": 122,    "title": "The Lord of the Rings The Return of the King",
     "genres": "adventure fantasy action",
     "cast": "elijah wood viggo mortensen ian mckellen orlando bloom",
     "director": "peter jackson",
     "keywords": "ring war battle gondor hobbit wizard elf courage",
     "overview": "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo.",
     "vote_average": 8.9, "release_year": 2003},

    {"id": 8681,   "title": "Gladiator",             "genres": "action drama adventure",
     "cast": "russell crowe joaquin phoenix connie nielsen oliver reed",
     "director": "ridley scott",
     "keywords": "roman empire revenge arena colosseum warrior emperor betrayal",
     "overview": "A Roman General is betrayed and his family murdered by a corrupt emperor.",
     "vote_average": 8.5, "release_year": 2000},

    {"id": 807,    "title": "Se7en",                 "genres": "crime mystery thriller drama",
     "cast": "brad pitt morgan freeman gwyneth paltrow kevin spacey",
     "director": "david fincher",
     "keywords": "serial killer detective seven sins mystery dark",
     "overview": "Two detectives hunt a serial killer who uses the seven deadly sins as his motives.",
     "vote_average": 8.6, "release_year": 1995},

    {"id": 550,    "title": "Fight Club",            "genres": "drama thriller",
     "cast": "brad pitt edward norton helena bonham carter",
     "director": "david fincher",
     "keywords": "identity anarchism underground club consumerism split personality",
     "overview": "An insomniac office worker and a devil-may-care soap maker form an underground fight club.",
     "vote_average": 8.8, "release_year": 1999},

    {"id": 289,    "title": "Casablanca",            "genres": "drama romance war",
     "cast": "humphrey bogart ingrid bergman paul henreid claude rains",
     "director": "michael curtiz",
     "keywords": "world war ii love sacrifice romance refugee classic",
     "overview": "A cynical nightclub owner must choose between love and virtue as a Nazi forces close in.",
     "vote_average": 8.5, "release_year": 1942},

    {"id": 637,    "title": "Life Is Beautiful",    "genres": "comedy drama romance war",
     "cast": "roberto benigni nicoletta braschi giorgio cantarini",
     "director": "roberto benigni",
     "keywords": "holocaust world war ii father son love humor survival",
     "overview": "A Jewish Italian man uses imagination to protect his son from the horrors of a concentration camp.",
     "vote_average": 8.6, "release_year": 1997},

    {"id": 372058, "title": "Your Name",             "genres": "animation romance drama fantasy",
     "cast": "ryunosuke kamiki mone kamishiraishi ryo narita aoi yuki",
     "director": "makoto shinkai",
     "keywords": "body swap comet fate love distance time anime",
     "overview": "Two strangers find themselves linked in a bizarre way, when they wake up one morning to find they have swapped bodies.",
     "vote_average": 8.5, "release_year": 2016},

    {"id": 129,    "title": "Spirited Away",         "genres": "animation adventure family fantasy",
     "cast": "daveigh chase suzanne pleshette jason marsden susan egan",
     "director": "hayao miyazaki",
     "keywords": "spirit world bathhouse girl courage transformation japanese folklore",
     "overview": "A young girl wanders into a world ruled by gods, witches, and spirits.",
     "vote_average": 8.6, "release_year": 2001},

    {"id": 10681,  "title": "WALL-E",                "genres": "animation science fiction family",
     "cast": "ben burtt elissa knight jeff garlin fred willard",
     "director": "andrew stanton",
     "keywords": "robot earth future love environment space trash",
     "overview": "In the distant future, a small waste-collecting robot inadvertently embarks on a space journey.",
     "vote_average": 8.4, "release_year": 2008},

    {"id": 508442, "title": "Soul",                  "genres": "animation comedy drama fantasy",
     "cast": "jamie foxx tina fey graham norton rachel house",
     "director": "pete docter",
     "keywords": "jazz music soul purpose life afterlife meaning pixar",
     "overview": "A jazz musician teams up with a soul to show her what life is all about.",
     "vote_average": 8.1, "release_year": 2020},

    {"id": 862,    "title": "Toy Story",             "genres": "animation comedy family",
     "cast": "tom hanks tim allen don rickles jim varney",
     "director": "john lasseter",
     "keywords": "toys friendship jealousy loyalty space cowboy adventure",
     "overview": "A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy.",
     "vote_average": 8.3, "release_year": 1995},

    {"id": 496243, "title": "Parasite",              "genres": "thriller drama",
     "cast": "song kang ho lee sun kyun cho yeo jeong choi woo shik",
     "director": "bong joon ho",
     "keywords": "class inequality family deception poverty wealth korean",
     "overview": "A poor family schemes to become employed by a wealthy family by infiltrating their household.",
     "vote_average": 8.5, "release_year": 2019},

    {"id": 244786, "title": "Whiplash",              "genres": "drama music",
     "cast": "miles teller j k simmons paul reiser melissa benoist",
     "director": "damien chazelle",
     "keywords": "drumming music obsession ambition perfectionism jazz",
     "overview": "A young drummer, determined to succeed, joins a top music academy where a ruthless instructor pushes him to his limits.",
     "vote_average": 8.5, "release_year": 2014},

    {"id": 313369, "title": "La La Land",            "genres": "drama comedy music romance",
     "cast": "ryan gosling emma stone john legend rosemarie dewitt",
     "director": "damien chazelle",
     "keywords": "jazz music love los angeles dreams ambition romance",
     "overview": "While navigating their careers in Los Angeles, a musician and an actress fall in love.",
     "vote_average": 8.0, "release_year": 2016},

    {"id": 539,    "title": "Psycho",                "genres": "horror mystery thriller",
     "cast": "anthony perkins janet leigh vera miles john gavin",
     "director": "alfred hitchcock",
     "keywords": "motel murder shower suspense classic horror mystery",
     "overview": "A Phoenix secretary embezzles forty thousand dollars from her employer's client, goes on the run, and checks into a remote motel.",
     "vote_average": 8.5, "release_year": 1960},

    {"id": 694,    "title": "The Shining",           "genres": "horror thriller drama",
     "cast": "jack nicholson shelley duvall danny lloyd scatman crothers",
     "director": "stanley kubrick",
     "keywords": "hotel isolation cabin fever supernatural madness twins maze",
     "overview": "A family heads to an isolated hotel for the winter where a sinister presence influences the father.",
     "vote_average": 8.4, "release_year": 1980},

    {"id": 4922,   "title": "Alien",                 "genres": "horror science fiction",
     "cast": "sigourney weaver tom skerritt john hurt veronica cartwright",
     "director": "ridley scott",
     "keywords": "alien creature space ship survival horror claustrophobia",
     "overview": "After a space merchant vessel perceives an unknown transmission as a distress call, its landing on the source moon causes one of the crew to be attacked.",
     "vote_average": 8.4, "release_year": 1979},

    {"id": 218,    "title": "The Terminator",        "genres": "action science fiction",
     "cast": "arnold schwarzenegger linda hamilton michael biehn paul winfield",
     "director": "james cameron",
     "keywords": "robot future time travel cyborg war survival machine",
     "overview": "A human soldier is sent from 2029 to 1984 to stop a cyborg killing machine, sent from the same year.",
     "vote_average": 8.0, "release_year": 1984},

    {"id": 361743, "title": "Top Gun Maverick",      "genres": "action drama",
     "cast": "tom cruise miles teller jennifer connelly jon hamm",
     "director": "joseph kosinski",
     "keywords": "pilot jet fighter navy training mission action sequel",
     "overview": "After thirty years, Maverick is still pushing the envelope as a top naval aviator.",
     "vote_average": 8.3, "release_year": 2022},

    {"id": 569094, "title": "Spider-Man No Way Home", "genres": "action adventure science fiction",
     "cast": "tom holland zendaya benedict cumberbatch jamie foxx",
     "director": "jon watts",
     "keywords": "spider man multiverse marvel doctor strange identity villain",
     "overview": "Spider-Man asks Doctor Strange for help after his identity is revealed, causing chaos.",
     "vote_average": 8.2, "release_year": 2021},

    {"id": 634649, "title": "Spider-Man Into the Spider-Verse",
     "genres": "animation action adventure science fiction",
     "cast": "shameik moore hailee steinfeld jake johnson lily tomlin",
     "director": "bob persichetti peter ramsey rodney rothman",
     "keywords": "spider man multiverse animation miles morales superhero",
     "overview": "Teen Miles Morales becomes the Spider-Man of his universe, and must join with five spider-people from other dimensions.",
     "vote_average": 8.4, "release_year": 2018},

    {"id": 293660, "title": "Deadpool",              "genres": "action comedy science fiction",
     "cast": "ryan reynolds morena baccarin ed skrein t j miller",
     "director": "tim miller",
     "keywords": "mercenary superhero fourth wall comedy anti hero regeneration",
     "overview": "A wisecracking mercenary gets experimented on and becomes immortal but ugly.",
     "vote_average": 7.9, "release_year": 2016},

    {"id": 348,    "title": "Alien Resurrection",   "genres": "science fiction action horror",
     "cast": "sigourney weaver winona ryder ron perlman",
     "director": "jean pierre jeunet",
     "keywords": "alien clone space ship survival creature resurrection",
     "overview": "Two hundred years after her death, Ellen Ripley is revived as a powerful human/alien hybrid clone.",
     "vote_average": 6.2, "release_year": 1997},

    {"id": 475557, "title": "Joker",                 "genres": "crime drama thriller",
     "cast": "joaquin phoenix robert de niro zazie beetz frances conroy",
     "director": "todd phillips",
     "keywords": "batman gotham villain mental illness clown society chaos",
     "overview": "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded by society.",
     "vote_average": 8.2, "release_year": 2019},

    {"id": 438631, "title": "Dune",                  "genres": "science fiction adventure drama",
     "cast": "timothee chalamet rebecca ferguson oscar isaac zendaya",
     "director": "denis villeneuve",
     "keywords": "desert planet spice sandworm empire war hero prophecy",
     "overview": "A noble family becomes embroiled in a war for the deadly and inhospitable desert planet Arrakis.",
     "vote_average": 8.0, "release_year": 2021},

    {"id": 346364, "title": "It",                    "genres": "horror drama",
     "cast": "bill skarsgard jaeden martell finn wolfhard sophia lillis",
     "director": "andy muschietti",
     "keywords": "clown fear children nightmare supernatural sewers horror",
     "overview": "In the summer of 1989, a group of children are terrorized by a shape-shifting entity.",
     "vote_average": 7.4, "release_year": 2017},

    {"id": 1726,   "title": "Iron Man",              "genres": "action science fiction adventure",
     "cast": "robert downey jr gwyneth paltrow jeff bridges terrence howard",
     "director": "jon favreau",
     "keywords": "billionaire suit technology armour marvel genius inventor",
     "overview": "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor.",
     "vote_average": 7.9, "release_year": 2008},

    {"id": 284053, "title": "Thor Ragnarok",         "genres": "action adventure comedy science fiction",
     "cast": "chris hemsworth tom hiddleston cate blanchett idris elba",
     "director": "taika waititi",
     "keywords": "thor hulk asgard gladiator comedy god hammer rainbow bridge",
     "overview": "Thor is imprisoned on the planet Sakaar and must race against time to return to Asgard.",
     "vote_average": 7.9, "release_year": 2017},

    {"id": 545611, "title": "Everything Everywhere All at Once",
     "genres": "action comedy science fiction drama",
     "cast": "michelle yeoh ke huy quan jamie lee curtis stephanie hsu",
     "director": "daniel kwan daniel scheinert",
     "keywords": "multiverse laundromat family taxes karate absurd everything",
     "overview": "An aging Chinese immigrant is swept up in an insane adventure where she must save the world.",
     "vote_average": 8.0, "release_year": 2022},

    {"id": 62,     "title": "2001 A Space Odyssey",  "genres": "science fiction mystery adventure",
     "cast": "keir dullea gary lockwood william sylvester",
     "director": "stanley kubrick",
     "keywords": "ai space monolith evolution hal astronaut ambiguous",
     "overview": "Humanity finds a mysterious artifact buried on the moon and sets off to find its origins.",
     "vote_average": 8.3, "release_year": 1968},

    {"id": 314,    "title": "Jaws",                  "genres": "thriller adventure horror drama",
     "cast": "roy scheider robert shaw richard dreyfuss lorraine gary",
     "director": "steven spielberg",
     "keywords": "shark ocean beach summer town terror police boat hunt",
     "overview": "A local sheriff, a marine biologist, and an old seafarer team up to hunt down a great white shark.",
     "vote_average": 8.0, "release_year": 1975},

    {"id": 335984, "title": "Blade Runner 2049",     "genres": "science fiction drama mystery",
     "cast": "ryan gosling harrison ford ana de armas sylvia hoeks",
     "director": "denis villeneuve",
     "keywords": "dystopia replicant future los angeles memory identity humanity",
     "overview": "A young blade runner's discovery of a long-buried secret leads him to track down former blade runner Rick Deckard.",
     "vote_average": 8.0, "release_year": 2017},

    {"id": 78,     "title": "Blade Runner",          "genres": "science fiction drama neo noir",
     "cast": "harrison ford rutger hauer sean young daryl hannah",
     "director": "ridley scott",
     "keywords": "replicant android dystopia future los angeles humanity identity",
     "overview": "A blade runner must pursue and terminate four replicants who stole a ship in space.",
     "vote_average": 8.1, "release_year": 1982},

    {"id": 106646, "title": "The Wolf of Wall Street", "genres": "drama comedy crime biography",
     "cast": "leonardo dicaprio jonah hill margot robbie matthew mcconaughey",
     "director": "martin scorsese",
     "keywords": "stockbroker fraud drugs wealth corruption greed excess",
     "overview": "Based on the true story of Jordan Belfort, from his rise to a wealthy stockbroker to his fall.",
     "vote_average": 8.2, "release_year": 2013},

    {"id": 244786, "title": "The Revenant",          "genres": "adventure drama western",
     "cast": "leonardo dicaprio tom hardy domhnall gleeson will poulter",
     "director": "alejandro inarritu",
     "keywords": "bear survival wilderness revenge frontier nature fur trapper",
     "overview": "A frontiersman on a fur trading expedition fights for survival after being mauled by a bear.",
     "vote_average": 8.0, "release_year": 2015},

    {"id": 98,     "title": "Goodfellas",            "genres": "drama crime biography",
     "cast": "ray liotta robert de niro joe pesci lorraine bracco",
     "director": "martin scorsese",
     "keywords": "mafia gangster mob new york crime loyalty violence drugs",
     "overview": "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill.",
     "vote_average": 8.7, "release_year": 1990},
]
